spring:
  application:
    name: reports
  data:
    mongodb:
      uri: mongodb://localhost:27017/reports-db  # Substitua com a URI do seu MongoDB
      database: reports  # Nome do seu banco de dados MongoDB

springdoc:
  swagger-ui:
    path: /

server:
  port: 8084

logging:
  level:
    org.springframework.data: DEBUG

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
